# ReplicaSet Configuration for NGINX Pods
apiVersion: apps/v1
kind: ReplicaSet

# Metadata section for naming, labeling, and documenting the ReplicaSet
metadata:
  name: nginx-replicaset  # Name of the ReplicaSet
  namespace: web-namespace  # Namespace for logical separation
  annotations:
    description: "ReplicaSet for managing 3 NGINX web server pods"
    owner: "DevOps Team"

# Specification section defining the desired state
spec:
  replicas: 3  # Ensure 3 replicas are always running

  # Selector defines how the ReplicaSet identifies pods to manage
  selector:
    matchLabels:
      app: nginx  # Manages pods with label app=nginx

  # Template for creating new pods
  template:
    metadata:
      labels:
        app: nginx  # Must match selector above
        tier: frontend  # Additional label for organizational purposes
    spec:
      containers:
      - name: nginx  # Name of the container
        image: nginx:1.25.2  # Specify a stable NGINX version
        ports:
        - containerPort: 80  # Port that NGINX listens on

        # Resource requests and limits
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

        # Liveness probe to check if the container is running
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10

        # Readiness probe to check if the container is ready to serve traffic
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
